apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2-deployment
spec:
  selector:
    matchLabels:
      app: nginx-2
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-2-service
spec:
  selector:
    app: nginx-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-2-ingress
spec:
  rules:
    - host: nginx2.jayforweb.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-2-service
                port:
                  number: 80